version: '3.7'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: fastapiapp
    environment:
      DB_PORT: 5433
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWROD: postgres
      DB_NAME: dev
    ports:
      - "8000:8000"
    depends_on:
      - database